name: Commit Report

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  commit_report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch all commits
        run: git fetch --prune --unshallow

      - name: Generate formatted commit report with changes
        run: |
          echo "# Commit Report for PR #${{ github.event.pull_request.number }}" > commit_report.txt
          echo "---" >> commit_report.txt
          echo "" >> commit_report.txt

          echo "## Summary" >> commit_report.txt
          echo "This report contains all commits and their associated changes for **PR #${{ github.event.pull_request.number}}**. Below you will find a list of commits and a detailed summary of what was changed." >> commit_report.txt
          echo "" >> commit_report.txt
          echo "---" >> commit_report.txt
          echo "" >> commit_report.txt

          echo "## Commits in this PR:" >> commit_report.txt
          BASE_SHA=$(git merge-base origin/main HEAD)
          git log $BASE_SHA..HEAD --oneline --pretty=format:"- **[%h]** %an, %ar: %s" >> commit_report.txt
          echo "" >> commit_report.txt
          echo "---" >> commit_report.txt
          echo "" >> commit_report.txt

          echo "## Detailed Changes:" >> commit_report.txt
          git log $BASE_SHA..HEAD --oneline --pretty=format:"%h" | while read commit_hash; do
            COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s" $commit_hash)
            echo "### Commit **[$commit_hash]** - $COMMIT_MESSAGE" >> commit_report.txt
            echo "\`\`\`diff" >> commit_report.txt
            git show $commit_hash --patch | tail -n +2 >> commit_report.txt
            echo "\`\`\`" >> commit_report.txt
            echo "" >> commit_report.txt
            echo "---" >> commit_report.txt
            echo "" >> commit_report.txt
          done

          echo "### End of Commit Report" >> commit_report.txt
          echo "" >> commit_report.txt

      - name: Upload commit report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: commit-report
          path: commit_report.txt

      - name: Post comment with download link
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO_URL="https://github.com/${{ github.repository }}"
          ARTIFACT_URL="$REPO_URL/actions/runs/${{ github.run_id }}"
          COMMENT_BODY="### 📄 Commit Report for PR #${PR_NUMBER}\n\nYou can download the commit report [here]($ARTIFACT_URL)."
          gh pr comment $PR_NUMBER --body "$COMMENT_BODY"
