name: Relatório de Commits

on:
  pull_request:
    types: [closed]

jobs:
  commit_report:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch all commits
        run: git fetch --prune --unshallow

      - name: Gerar relatório de commits em HTML
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.sha }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          REPORT_PATH="commit_report.html"
          echo "<!DOCTYPE html>" > $REPORT_PATH
          echo "<html lang='pt-BR'>" >> $REPORT_PATH
          echo "<head>" >> $REPORT_PATH
          echo "  <meta charset='UTF-8'>" >> $REPORT_PATH
          echo "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>" >> $REPORT_PATH
          echo "  <title>Relatório de Commits</title>" >> $REPORT_PATH
          echo "  <style>" >> $REPORT_PATH
          echo "    body { font-family: Arial, sans-serif; line-height: 1.6; margin: 20px; }" >> $REPORT_PATH
          echo "    h1, h2, h3 { color: #333; }" >> $REPORT_PATH
          echo "    .commit { margin-bottom: 20px; }" >> $REPORT_PATH
          echo "    .divider { border-top: 1px solid #ddd; margin: 20px 0; }" >> $REPORT_PATH
          echo "  </style>" >> $REPORT_PATH
          echo "</head>" >> $REPORT_PATH
          echo "<body>" >> $REPORT_PATH

          echo "<h1>Relatório de Commits para PR #${PR_NUMBER}</h1>" >> $REPORT_PATH
          echo "<p>Este relatório contém todos os commits associados ao <strong>PR #${PR_NUMBER}</strong>.</p>" >> $REPORT_PATH
          echo "<hr class='divider'>" >> $REPORT_PATH

          echo "<h2>Commits neste PR:</h2>" >> $REPORT_PATH
          git log $BASE_SHA..$HEAD_SHA --oneline --pretty=format:"<div class='commit'><h3>Commit [%h]</h3><p><strong>Autor:</strong> %an, <strong>Data:</strong> %ar</p><p><strong>Mensagem:</strong> %s</p></div>" >> $REPORT_PATH

          echo "</body>" >> $REPORT_PATH
          echo "</html>" >> $REPORT_PATH

      - name: Upload HTML commit report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: commit-report-html
          path: commit_report.html

      - name: Publicar comentário com link de download
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const prNumber = ${{ github.event.pull_request.number }};
            const repoUrl = `https://github.com/${{ github.repository }}`;
            const artifactUrl = `${repoUrl}/actions/runs/${{ github.run_id }}`;
            const commentBody = `
              ### 📄 Relatório de Commits para PR #${prNumber}

              Você pode baixar o relatório detalhado em HTML [aqui](${artifactUrl}).
            `;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: prNumber,
              body: commentBody,
            });