name: Commit Report

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  commit_report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch all commits
        run: git fetch --prune --unshallow

      - name: Get commits for PR
        run: |
          echo "### Commit Report for PR #${{ github.event.pull_request.number }}" > commit_report.txt
          echo "===================================" >> commit_report.txt
          echo "This report contains all commits and their changes in PR #${{ github.event.pull_request.number }}." >> commit_report.txt
          echo "" >> commit_report.txt
          
          BASE_SHA=$(git merge-base origin/main HEAD)
          
          echo "#### Commits in this PR:" >> commit_report.txt
          echo "" >> commit_report.txt
          git log $BASE_SHA..HEAD --oneline --pretty=format:"%h - %an, %ar : %s" >> commit_report.txt
          echo "" >> commit_report.txt

          echo "===================================" >> commit_report.txt
          echo "#### Commit Changes:" >> commit_report.txt
          echo "" >> commit_report.txt
          git log $BASE_SHA..HEAD --oneline --pretty=format:"%h" | while read commit_hash; do
            echo "##### Changes for commit $commit_hash:" >> commit_report.txt
            git show --stat $commit_hash >> commit_report.txt
            echo "" >> commit_report.txt
          done

          echo "===================================" >> commit_report.txt
          echo "### End of Commit Report" >> commit_report.txt
          echo "" >> commit_report.txt

      - name: Create tag for release
        run: |
          # Create a tag for the release
          TAG_NAME="pr-${{ github.event.pull_request.number }}-report"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: commit_report.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create comment on PR with download link
        if: github.event.pull_request
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/tag/pr-${{ github.event.pull_request.number }}-report"
          COMMENT_BODY="The commit report for this PR is available for download: $RELEASE_URL"
          gh pr comment $PR_NUMBER --body "$COMMENT_BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
